#!/usr/bin/env python3
"""
setup_orchestrator.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Amazon Empire — Account Setup & Config Orchestrator
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Runs automatically. Pauses ONLY when it needs something from you.
Saves progress. Resume any time by re-running.

Usage:
    python setup_orchestrator.py
    python setup_orchestrator.py --reset       # Start over
    python setup_orchestrator.py --status      # Show current status
"""

import os, sys, json, time, subprocess, webbrowser, shutil, platform
from pathlib import Path
from datetime import datetime
from typing import Optional

# ── Colors ────────────────────────────────────────────────────────────────────
class C:
    HEADER  = '\033[95m'
    BLUE    = '\033[94m'
    CYAN    = '\033[96m'
    GREEN   = '\033[92m'
    YELLOW  = '\033[93m'
    RED     = '\033[91m'
    BOLD    = '\033[1m'
    DIM     = '\033[2m'
    END     = '\033[0m'

def bold(t): return f"{C.BOLD}{t}{C.END}"
def green(t): return f"{C.GREEN}{t}{C.END}"
def yellow(t): return f"{C.YELLOW}{t}{C.END}"
def red(t): return f"{C.RED}{t}{C.END}"
def cyan(t): return f"{C.CYAN}{t}{C.END}"
def dim(t): return f"{C.DIM}{t}{C.END}"

STATE_FILE = Path("./setup_state.json")
ENV_FILE   = Path("./.env")

# ── State management ──────────────────────────────────────────────────────────
def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {
        "completed_steps": [],
        "credentials": {},
        "started_at": datetime.now().isoformat(),
        "last_run": None,
        "github_repo": None,
        "github_username": None,
    }

def save_state(state: dict):
    STATE_FILE.write_text(json.dumps(state, indent=2))

def mark_done(state: dict, step: str):
    if step not in state["completed_steps"]:
        state["completed_steps"].append(step)
    save_state(state)

def is_done(state: dict, step: str) -> bool:
    return step in state["completed_steps"]

def save_cred(state: dict, key: str, value: str):
    state["credentials"][key] = value
    save_state(state)
    # Also write to .env file
    write_env(state)

def write_env(state: dict):
    """Write all collected credentials to .env"""
    creds = state.get("credentials", {})
    repo  = state.get("github_repo", "YOUR_USERNAME/amazon-associates-content-site")

    lines = [
        "# Amazon Empire — Business 1 (Associates)",
        f"# Generated by setup_orchestrator.py on {datetime.now():%Y-%m-%d %H:%M}",
        "# ─────────────────────────────────────────",
        "",
        "# AI",
        f"ANTHROPIC_API_KEY={creds.get('ANTHROPIC_API_KEY', '')}",
        "",
        "# Amazon",
        f"AMAZON_ASSOCIATE_TAG={creds.get('AMAZON_ASSOCIATE_TAG', '')}",
        f"AMAZON_ACCESS_KEY={creds.get('AMAZON_ACCESS_KEY', '')}",
        f"AMAZON_SECRET_KEY={creds.get('AMAZON_SECRET_KEY', '')}",
        "AMAZON_MARKETPLACE=www.amazon.com",
        "",
        "# GitHub",
        f"GITHUB_TOKEN={creds.get('GITHUB_TOKEN', '')}",
        f"GITHUB_REPO={repo}",
        "GITHUB_BRANCH=main",
        "",
        "# Email alerts",
        f"GMAIL_SENDER={creds.get('GMAIL_SENDER', '')}",
        f"GMAIL_APP_PASSWORD={creds.get('GMAIL_APP_PASSWORD', '')}",
        f"GMAIL_TO={creds.get('GMAIL_TO', creds.get('GMAIL_SENDER', ''))}",
        "",
        "# App settings",
        "DB_PATH=./data/business1.db",
        "ARTICLES_PER_RUN=3",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines))

# ── UI helpers ─────────────────────────────────────────────────────────────────
def header(title: str, subtitle: str = ""):
    width = 62
    print()
    print("┌" + "─" * width + "┐")
    print(f"│  {bold(title):<{width-2}}│")
    if subtitle:
        print(f"│  {dim(subtitle):<{width-2}}│")
    print("└" + "─" * width + "┘")

def section(emoji: str, title: str):
    print(f"\n{bold(f'{emoji}  {title}')}")
    print("─" * 50)

def pause(msg: str = "Press ENTER when done...") -> str:
    print(f"\n{yellow('⏸  ACTION NEEDED')} → {msg}")
    return input(f"{C.YELLOW}   → {C.END}").strip()

def ask(prompt: str, required: bool = True, secret: bool = False, example: str = "") -> str:
    """Prompt user for input. Loops until valid if required."""
    if example:
        print(f"   {dim(f'Example: {example}')}")
    while True:
        try:
            if secret:
                import getpass
                val = getpass.getpass(f"{cyan('  ▶')} {prompt}: ").strip()
            else:
                val = input(f"{cyan('  ▶')} {prompt}: ").strip()
        except (KeyboardInterrupt, EOFError):
            print(f"\n{yellow('Paused. Re-run this script to continue.')}")
            sys.exit(0)
        if val or not required:
            return val
        print(f"   {red('This field is required. Try again.')}")

def open_url(url: str, label: str = ""):
    """Open a URL in the default browser."""
    print(f"\n   {cyan('→')} Opening: {bold(url)}")
    if label:
        print(f"   {dim(label)}")
    time.sleep(0.5)
    webbrowser.open(url)
    time.sleep(1)

def step_header(num: int, total: int, title: str, status: str = ""):
    badge = green("✓ DONE") if status == "done" else yellow("→ NEXT") if status == "current" else dim("○ LATER")
    print(f"\n  [{num}/{total}] {bold(title)}  {badge}")

def progress_bar(state: dict, steps: list):
    done = sum(1 for s in steps if is_done(state, s["id"]))
    total = len(steps)
    pct = int((done / total) * 40)
    bar = "█" * pct + "░" * (40 - pct)
    print(f"\n  Progress: [{green(bar)}] {done}/{total} steps complete")

def print_status(state: dict, steps: list):
    header("SETUP STATUS", "Amazon Associates Content Site")
    progress_bar(state, steps)
    print()
    for i, step in enumerate(steps, 1):
        done = is_done(state, step["id"])
        icon = green("✓") if done else dim("○")
        print(f"  {icon}  {step['name']}")

    print(f"\n  {dim('Credentials saved:')}")
    for k, v in state.get("credentials", {}).items():
        masked = v[:8] + "..." if len(v) > 8 else "***"
        print(f"     {k} = {masked}")

    if ENV_FILE.exists():
        print(f"\n  {green('.env file exists')}: {ENV_FILE.absolute()}")

# ── Step implementations ───────────────────────────────────────────────────────

def step_verify_github(state: dict):
    """Verify GitHub account and get username."""
    section("🐙", "STEP 1: GitHub Account")
    print("  Your GitHub account is needed to host the website (free).")
    print("  It looks like you're already signed in based on your browser.")
    print()

    username = ask("What is your GitHub username?", example="ViciousStudio-tech")
    state["github_username"] = username
    state["github_repo"] = f"{username}/amazon-associates-content-site"
    save_state(state)

    print(f"\n  {green('✓')} GitHub username saved: {bold(username)}")
    print(f"  {green('✓')} Repo will be: {bold(state['github_repo'])}")
    mark_done(state, "github_account")


def step_create_github_repo(state: dict):
    """Guide creation of GitHub repo."""
    section("📁", "STEP 2: Create GitHub Repository")

    if state.get("github_username"):
        repo_name = "amazon-associates-content-site"
        username = state["github_username"]
        print(f"  Creating: {bold(f'github.com/{username}/{repo_name}')}")
        print()

        open_url(
            f"https://github.com/new",
            "Create a new GitHub repository"
        )
        print("""
  Fill in the form as follows:
  ┌─────────────────────────────────────────────────┐
  │  Repository name:  amazon-associates-content-site│
  │  Description:      Amazon affiliate content site │
  │  Visibility:       ● Public                      │
  │  Add README:       ☑ ON                          │
  └─────────────────────────────────────────────────┘
        """)
        pause("After you click 'Create repository', press ENTER here")

        confirmed = ask("Repo created successfully? (yes/no)", example="yes")
        if confirmed.lower() in ("yes", "y"):
            print(f"  {green('✓')} Repository created!")
            mark_done(state, "github_repo")


def step_enable_github_pages(state: dict):
    """Enable GitHub Pages on the repo."""
    section("🌐", "STEP 3: Enable GitHub Pages")
    username = state.get("github_username", "YOUR_USERNAME")
    repo = "amazon-associates-content-site"

    open_url(
        f"https://github.com/{username}/{repo}/settings/pages",
        "GitHub Pages settings"
    )
    print("""
  In the Pages settings:
  ┌─────────────────────────────────────────────────┐
  │  Source:  Deploy from a branch                  │
  │  Branch:  main    /  (root)                     │
  │  Click:   Save                                  │
  └─────────────────────────────────────────────────┘
    """)
    pause("After clicking Save, press ENTER here")

    site_url = f"https://{username}.github.io/{repo}"
    print(f"\n  {green('✓')} Your site will be live at: {bold(site_url)}")
    save_cred(state, "SITE_URL", site_url)
    mark_done(state, "github_pages")


def step_github_pat(state: dict):
    """Create a GitHub Personal Access Token."""
    section("🔑", "STEP 4: GitHub Personal Access Token (PAT)")
    print("  This lets the automation push articles to your repo automatically.")
    print()

    open_url(
        "https://github.com/settings/tokens/new",
        "Create a new Personal Access Token"
    )
    print("""
  Fill in the form:
  ┌─────────────────────────────────────────────────┐
  │  Note:       Amazon Empire Bot                  │
  │  Expiration: No expiration (or 1 year)          │
  │  Scopes:     ☑ repo  (check the top 'repo' box) │
  └─────────────────────────────────────────────────┘
  Then click "Generate token" — COPY IT immediately,
  it won't be shown again!
    """)
    pause("Generate the token, copy it, then press ENTER")

    token = ask("Paste your GitHub token here", secret=True, example="ghp_xxxxxxxxxxxx")
    if token:
        save_cred(state, "GITHUB_TOKEN", token)
        print(f"  {green('✓')} GitHub token saved to .env")
        mark_done(state, "github_pat")


def step_anthropic_api(state: dict):
    """Get Anthropic Claude API key."""
    section("🤖", "STEP 5: Anthropic Claude API Key")
    print("  Claude writes all the articles. API key needed to use it.")
    print()

    open_url(
        "https://console.anthropic.com/settings/keys",
        "Anthropic Console — API Keys"
    )
    print("""
  Steps:
  1. Sign in (or create account if new)
  2. Click "Create Key"
  3. Name it: Amazon Empire
  4. COPY the key — it won't be shown again
    """)
    pause("Create the key and copy it, then press ENTER")

    key = ask("Paste your Anthropic API key", secret=True, example="sk-ant-...")
    if key:
        save_cred(state, "ANTHROPIC_API_KEY", key)

        # Quick validation
        print("  Testing API key...")
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=key)
            resp = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=10,
                messages=[{"role": "user", "content": "Say OK"}]
            )
            print(f"  {green('✓')} API key works! Response: {resp.content[0].text}")
        except ImportError:
            print(f"  {yellow('⚠')} anthropic package not installed yet — will test after pip install")
        except Exception as e:
            print(f"  {red('✗')} Key test failed: {e}")
            retry = ask("Try a different key? (yes/no)")
            if retry.lower() in ("yes", "y"):
                return step_anthropic_api(state)

        mark_done(state, "anthropic_api")


def step_amazon_associates(state: dict):
    """Guide Amazon Associates application."""
    section("🛒", "STEP 6: Amazon Associates Account")
    print("  Free affiliate program. You earn 1-10% when visitors buy on Amazon.")
    print()

    open_url(
        "https://affiliate-program.amazon.com",
        "Amazon Associates signup"
    )
    print("""
  Steps:
  1. Click "Sign up" (use your existing Amazon account)
  2. Account info: fill your name, address
  3. Website list: enter your GitHub Pages URL:
     https://YOUR_USERNAME.github.io/amazon-associates-content-site
  4. Store ID: choose a short memorable name (e.g. 'viciousstudio')
  5. How you drive traffic: select 'Content/Niche site'
  6. Complete the rest and submit

  ⚠ You'll get a TEMPORARY tag immediately (e.g. viciousstudio-20)
    even before final approval. Use this to start!
    """)

    tag = ask(
        "What is your Associate Store ID / Tag?",
        example="viciousstudio-20"
    )
    if tag:
        if not tag.endswith("-20"):
            tag = tag.rstrip("-") + "-20"
        save_cred(state, "AMAZON_ASSOCIATE_TAG", tag)
        print(f"  {green('✓')} Associate tag saved: {bold(tag)}")
        mark_done(state, "amazon_associates")

    print(f"""
  {yellow('Note:')} Full approval takes up to 48 hours. During review:
  - Your tag works immediately for tracking
  - You have 180 days to get 3 qualifying sales
  - The automation will use your tag from day 1
    """)


def step_openai_api(state: dict):
    """Get OpenAI API key for image generation (optional for now)."""
    section("🎨", "STEP 7: OpenAI API Key (for Merch images — skip for now)")
    print("  This is needed for Business 2 (Merch on Demand), not Business 1.")
    print("  We can set it up now or come back to it later.")
    print()

    skip = ask("Skip OpenAI setup for now? (yes/no)", example="yes")
    if skip.lower() in ("yes", "y"):
        print(f"  {dim('Skipping OpenAI — come back when building Business 2')}")
        mark_done(state, "openai_skip")
        return

    open_url(
        "https://platform.openai.com/api-keys",
        "OpenAI Platform — API Keys"
    )
    pause("Create a key, add $20 credit, copy the key, then press ENTER")

    key = ask("Paste your OpenAI API key", secret=True, example="sk-proj-...")
    if key:
        save_cred(state, "OPENAI_API_KEY", key)
        print(f"  {green('✓')} OpenAI key saved")
        mark_done(state, "openai_api")


def step_gmail_app_password(state: dict):
    """Set up Gmail for automated email alerts."""
    section("📧", "STEP 8: Gmail App Password (for email alerts)")
    print("  The system emails you a daily digest + alerts when things break.")
    print("  Requires a Gmail account with 2-factor authentication enabled.")
    print()

    gmail = ask("What Gmail address should receive the alerts?", example="you@gmail.com")
    save_cred(state, "GMAIL_SENDER", gmail)
    save_cred(state, "GMAIL_TO", gmail)

    open_url(
        "https://myaccount.google.com/apppasswords",
        "Google Account — App Passwords"
    )
    print("""
  Steps:
  1. Sign in if prompted
  2. App name: type "Amazon Empire"
  3. Click "Create"
  4. Copy the 16-character password shown (format: xxxx xxxx xxxx xxxx)
    """)
    pause("Create the app password and copy it, then press ENTER")

    pwd = ask("Paste the 16-character app password", secret=True, example="xxxx xxxx xxxx xxxx")
    if pwd:
        save_cred(state, "GMAIL_APP_PASSWORD", pwd)
        print(f"  {green('✓')} Gmail credentials saved")
        mark_done(state, "gmail_app_password")


def step_install_packages(state: dict):
    """Install required Python packages."""
    section("📦", "STEP 9: Install Python Packages")

    packages = ["anthropic", "requests", "python-dotenv"]
    print(f"  Installing: {', '.join(packages)}")
    print()

    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install"] + packages + ["--quiet"],
            capture_output=True, text=True, timeout=120
        )
        if result.returncode == 0:
            print(f"  {green('✓')} All packages installed")
            mark_done(state, "packages_installed")
        else:
            print(f"  {yellow('⚠')} pip output: {result.stderr[:300]}")
            manual = ask("Try manual install? Run: pip install anthropic requests python-dotenv (yes/no)")
    except Exception as e:
        print(f"  {red('Error:')} {e}")
        print(f"  Run manually: pip install anthropic requests python-dotenv")


def step_first_pipeline_run(state: dict):
    """Run the first article pipeline."""
    section("🚀", "STEP 10: First Pipeline Run")
    print("  Running: keyword finder → article writer → publisher")
    print("  This will write your first 3 articles and push them live.")
    print()

    creds = state.get("credentials", {})
    missing = []
    required = ["ANTHROPIC_API_KEY", "GITHUB_TOKEN", "AMAZON_ASSOCIATE_TAG"]
    for k in required:
        if not creds.get(k):
            missing.append(k)

    if missing:
        print(f"  {red('Missing credentials:')} {', '.join(missing)}")
        print(f"  {yellow('Go back and complete those steps first.')}")
        return

    print(f"  {green('All required credentials present. Starting pipeline...')}\n")

    for script in ["b1_keyword_finder.py", "b1_article_writer.py", "b1_publisher.py"]:
        if not Path(script).exists():
            print(f"  {yellow('⚠')} {script} not found — make sure you unzipped the project files here")
            continue

        print(f"  Running {script}...")
        start = time.time()
        try:
            result = subprocess.run(
                [sys.executable, script],
                timeout=300,
                text=True
            )
            elapsed = round(time.time() - start, 1)
            if result.returncode == 0:
                print(f"  {green('✓')} {script} completed in {elapsed}s")
            else:
                print(f"  {red('✗')} {script} failed — check logs/ folder for details")
                cont = ask("Continue to next step anyway? (yes/no)")
                if cont.lower() not in ("yes","y"):
                    return
        except subprocess.TimeoutExpired:
            print(f"  {red('✗')} {script} timed out (>5min). Check logs/")

    username = state.get("github_username", "YOUR_USERNAME")
    site_url = f"https://{username}.github.io/amazon-associates-content-site"
    print(f"""
  {green('🎉 Pipeline complete!')}

  Your site: {bold(site_url)}
  Articles published: check _posts/ folder
  Database: data/business1.db

  GitHub will rebuild your site in 2-3 minutes.
  First articles appear in Google within 3-7 days.
    """)
    mark_done(state, "first_pipeline_run")


def step_github_actions_secrets(state: dict):
    """Add secrets to GitHub Actions."""
    section("⚙️", "STEP 11: GitHub Actions Secrets (enables automated weekly runs)")
    username = state.get("github_username", "YOUR_USERNAME")
    repo = "amazon-associates-content-site"

    open_url(
        f"https://github.com/{username}/{repo}/settings/secrets/actions/new",
        "Add GitHub Actions secret"
    )
    print("""
  Add these secrets one by one (Settings → Secrets → New repository secret):

  Secret name              Value from
  ─────────────────────────────────────────────────
  ANTHROPIC_API_KEY      → your Claude API key
  AMAZON_ASSOCIATE_TAG   → e.g. viciousstudio-20
  GH_PAT                 → your GitHub token
  GMAIL_APP_PASSWORD     → your Gmail app password
  GMAIL_SENDER           → your Gmail address
  GMAIL_TO               → your Gmail address

  After adding all 6 secrets, GitHub Actions will run
  the pipeline AUTOMATICALLY every Sunday. No cron server needed.
    """)
    pause("Add all 6 secrets and press ENTER when done")
    mark_done(state, "github_actions_secrets")
    print(f"  {green('✓')} GitHub Actions configured — automation is live!")


# ── Main orchestrator ──────────────────────────────────────────────────────────
STEPS = [
    {"id": "github_account",         "name": "GitHub account verified",        "fn": step_verify_github},
    {"id": "github_repo",            "name": "GitHub repo created",            "fn": step_create_github_repo},
    {"id": "github_pages",           "name": "GitHub Pages enabled",           "fn": step_enable_github_pages},
    {"id": "github_pat",             "name": "GitHub Personal Access Token",   "fn": step_github_pat},
    {"id": "anthropic_api",          "name": "Anthropic API key",              "fn": step_anthropic_api},
    {"id": "amazon_associates",      "name": "Amazon Associates account",      "fn": step_amazon_associates},
    {"id": "openai_skip",            "name": "OpenAI API (skip for B1)",       "fn": step_openai_api},
    {"id": "gmail_app_password",     "name": "Gmail app password",             "fn": step_gmail_app_password},
    {"id": "packages_installed",     "name": "Python packages installed",      "fn": step_install_packages},
    {"id": "first_pipeline_run",     "name": "First pipeline run",             "fn": step_first_pipeline_run},
    {"id": "github_actions_secrets", "name": "GitHub Actions secrets added",   "fn": step_github_actions_secrets},
]

def main():
    # Handle CLI flags
    if "--reset" in sys.argv:
        if STATE_FILE.exists():
            STATE_FILE.unlink()
        print("State reset. Re-run without --reset to start fresh.")
        sys.exit(0)

    state = load_state()
    state["last_run"] = datetime.now().isoformat()
    save_state(state)

    if "--status" in sys.argv:
        print_status(state, STEPS)
        sys.exit(0)

    # Clear screen
    os.system('cls' if platform.system() == 'Windows' else 'clear')

    # Header
    print()
    print(f"  {bold('AMAZON EMPIRE')} {dim('— Account Setup Orchestrator')}")
    print(f"  {dim('Runs automatically. Pauses only when it needs you.')}")
    print()

    progress_bar(state, STEPS)

    # Count remaining
    remaining = [s for s in STEPS if not is_done(state, s["id"])]
    done_count = len(STEPS) - len(remaining)

    if not remaining:
        print(f"\n  {green('🎉 ALL SETUP COMPLETE!')}")
        print(f"  Your pipeline is live and running automatically.")
        print_status(state, STEPS)
        sys.exit(0)

    if done_count > 0:
        print(f"\n  {green(f'Resuming from step {done_count + 1}')}")
        print(f"  {dim('Completed steps will be skipped automatically.')}")

    print(f"\n  {yellow('⚡')} {len(remaining)} steps remaining. Press Ctrl+C at any time to pause.\n")
    time.sleep(1)

    # Run each incomplete step
    for step in STEPS:
        if is_done(state, step["id"]):
            print(f"  {green('✓')} {step['name']} {dim('(already done)')}")
            continue

        try:
            step["fn"](state)
        except (KeyboardInterrupt, EOFError):
            print(f"\n\n  {yellow('Paused.')} Run this script again to resume.")
            sys.exit(0)
        except Exception as e:
            print(f"\n  {red('Error in step:')} {e}")
            cont = input(f"  {yellow('Continue to next step? (yes/no): ')}").strip()
            if cont.lower() not in ("yes", "y"):
                print("  Paused. Re-run to resume.")
                sys.exit(0)

    # Final summary
    print()
    print("┌" + "─" * 60 + "┐")
    print(f"│  {bold('🎉  ALL STEPS COMPLETE!'):<60}│")
    print(f"│  {dim('Your Amazon Associates pipeline is live.'):<60}│")
    print("└" + "─" * 60 + "┘")
    username = state.get("github_username", "YOUR_USERNAME")
    site_url = f"https://{username}.github.io/amazon-associates-content-site"
    print(f"""
  WHAT HAPPENS NOW:
  ─────────────────────────────────────────────────────
  • Your site:     {bold(site_url)}
  • New articles:  Every Sunday (GitHub Actions)
  • Monitoring:    Every 6 hours (GitHub Actions)
  • Daily digest:  Email arrives Monday morning

  NEXT STEP:
  • After your Amazon Associates is approved (~24-48h):
    Go to Associates dashboard → Tools → Product Advertising API
    Apply for PA-API access (adds live prices to articles)
    Run: python setup_orchestrator.py  (to add PA-API keys)
    """)


if __name__ == "__main__":
    main()
